<p class="help"><img class="icon" src="../themes/icons/help.svg" loading="lazy" alt="ℹ️"> These settings are for sites without special configurations.<br/>
For sites with known responses the extension uses the data provided by the site.</p>

<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
		<label class="group-name" for="rate_limit_window">Rate limit window (in seconds)</label>
		<div class="group-controls">
			<input type="number" min="1" value="<?php echo $this->rateLimitWindow; ?>" class="w50" name="rate_limit_window"
			id="rate_limit_window" required="required" />
		</div>
	</div>
	<div class="form-group">
		<label class="group-name" for="rate_limit_count">Max hits during the window</label>
		<div class="group-controls">
			<input type="number" min="1" value="<?php echo $this->maxRateLimitCount; ?>" class="w50" name="rate_limit_count"
				id="rate_limit_count" required="required" />
		</div>
	</div>
	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
			<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
		</div>
	</div>
</form>